### ISSUE TITLE
package.json was deleted

### ISSUE THREAD

**Issue by seankim658** [biocompute-objects/playbook-partnership#45]
It seems in commit 7358ffc the `package.json` file was deleted. 

@HadleyKing Correct me if I'm mistaken, but I believe this might've been accidentally?

**Comment by HadleyKing** [comment]
I did delete it on purpose. Since the `package.json` file is not critical for the running of the app and is generated automatically when you run `npm install` I removed it. When I run the app locally I use `3000` for BCO and change the port for playbook, which requires a flag in the `package.json`. But you can put it back. Especially since the upstream repo keeps it, it may cause conflicts when merging.
